<?php

$headlines = 
Array(
"Designer Family  property  Of Space And Sophistication",
"Magnificent Art Deco Style Family Home On Quiet Street",
"Cheapest House On A Private Street",
"A Grand  Resort-Style Entertainer",
"A Feel Good Family Home Amongst Leafy Serenity",
"Family Perfection In A Dress Circle Setting",
"Large Family Home In A Great Location",
"Stylish Entertainer Close To Local Attractions",
"Beautiful Residence Selling Below Bank Valuation",
"Open Plan Living with Private Courtyard",
"Outstanding Location  Luxurious Renovation",
"Gorgeous Older Style Stacked with Lifestyle Advantages",
"A Resort Style Lifestyle With Water Views",
"Character Filled Residence In The Heart Of  SUBURB ",
"Convenient Location On A Massive Flat Block",
"Spacious Entertainer In Quiet And Convenient Location",
"Immaculate And Elevated Home On  lotsize sqm Allotment",
"Huge Family Home in Quiet Position",
"Double Storey Brick-And-Weatherboard Dwelling",
"Perfect Family Home or Investment Opportunity",
"Peaceful And Tranquil Setting",
"Cozy Home With A Great Shed",
"Resort Living with So Much Style",
"Generous Family Home Near To Park",
"Family Treasure Trove",
"Perfect Family Home In A Cul De Sac",
"Ultra Modern With So Much Space",
"One Level With All New Sparkle",
"Classic Queenslander Charm With Designer Style And Luxury",
"Modern Lifestyle & Perfect Location",
"Prestigious Family Home In Outstanding Location",
"An Iconic Waterfront Community",
"Resplendent in Design and Liveability",
"Family Home On A Large Sunny Block",
"Character Home With Potential To Renovate",
"Peaceful Living with Uninterrupted Urban Views",
"Contemporary Chic With Parkside Poise",
" lotsize sqm Of Luxury Living",
"Sophisticated Haven In A Premium Lifestyle Enclave",
"Superb Design Generous Dimensions",
"An Enviable Country Retreat That Will Excite And Inspire",
"An Awe-Inspiring Beachfront Retreat",
"Whale Watchers Paradise",
"Superbly Renovated Family Masterpiece In  suburb ",
"Your Chance For Uninterrupted Water Views",
"Top Floor  property  For Relaxed Beachside Lifestyle",
"Character And Charm With Modern Style",
"Enveloped In An Intoxicating Aura Of Rural Seclusion",
"Contemporary Living & Urban Style",
"Relax In Blissful Sun-Soaked Luxury By The Beach",
"Charming Victorian in Prized Position",
"Cutting Edge Streamlined Luxury Designer  property ",
"First Class Hidden Jewel",
"Cul-De-Sac Brick Beauty",
"Acreage Living At Its Absolute Finest",
"Ultimate Riverfront Lifestyle",
"The Ease Of Single-Level Living In A Prime Lifestyle Pocket",
"Elegant Cozy  property  In An Idyllic Waterside Locale",
"Gorgeous  Warm  Opulent Living With A Fabulous Feel",
"Family And Entertaining Bonanza",
"Endearing Elegance With Low Maintenance Appeal",
"Elite Family Excellence With Soaring Views",
"A Perfect Lifestyle Property To Treasure",
"Front Row Seat For Spectacular Sunsets",
"Designer Dimensions In A Prized Position",
"Assured and Carefree Contemporary Living",
"Your own peace of paradise awaits you.",
"Character  Space And Timeless Elegance",
"Architecturally Designed With Style",
"City Convenience  Country Serenity",
"Picturesque Private Retreat",
"A World Of Luxury  Elegance And Prestige",
"A Dream Location Packed With Potential",
"A Grand Slam Winner With Space And Style",
"Live In The Lap Of Luxury",
"Style  Class and Sophistication",
"Luxury Coastal Lifestyle Beckons",
"Versatile Style With Vintage Appeal",
"Spacious Vintage-Chic Modern Style",
"Elegantly Decorated Home With Iconic Views",
"Private  Safe  Secluded and Tranquil With Water Views",
"Thinking Of A Sea Change? Here Is Your Opportunity",
"Prime Waterfront Position & the Ultimate In Luxury Living",
"Unique Opportunity in  Suburb ",
"The Size Will Surprise",
"Great  storey  Entertainer",
"Perfect For The Growing Family",
"Private  Easy-Care Lifestyle",
"Secure Your  suburb  Address Today",
"Get A Foot Into  Suburb ",
"Prestigious Address Overlooking Park",
"Position  Position  Position",
"Sought After Complex So Close To Everything",
"Private  Easy-Care Lifestyle",
"Worst House Best Street",
"Classic Family Home In  suburb ",
"Unique Inner City Living",
"Cosmopolitan City Living At Its Best",
"Lavish Luxury In Landmark City Surroundings",
"Unique And Luxurious Haven",
"Waking To Breath taking Water And Tranquil Views",
"Renovators Dream",
"Huge Flat Block  Huge Potential",
"A Statement Of Modesty",
"Spacious  Versatile And Wonderfully Serene",
"Splendid Waterfront Lifestyle",
"Spacious  Private & Quality Modern Home",
"Eye-catching Property With Picturesque Mountain Views",
"Craftsman Built Cozy Home",
"Rare Quality & Style",
"Immaculate House  Blue Ribbon Location",
"Position Plus Potential",
"Supersized Prestigious Home With Mountain Views",
"Charming Family Appeal With Endless Possibilities",
"Luxurious Lifestyle Living Or Ideal Investment",
"Affordable First Home Or Investment Opportunity",
"Exceptionally Spacious  Flexible  With Bushland Ambience",
"Versatile Family Gem",
"Sunshine Filled Beach Escape",
"Private Cozy Family Favourite",
"A Corner Of Comfortability",
"Timeless Elegance And A Zen Ambience",
"Stunning And Unique Offering Urban living At Its Best!",
"Large Family Home With Side Access",
"Prime Position!",
"Start Living Your Dream",
"Stylish  Contemporary Home In Elevated Location",
"Location  Convenience  Lifestyle",
"Ground Floor Courtyard Unit Perfect For Pet Lovers",
"Post War Home With Unlimited Potential",
"Rare Opportunity Awaits Along The River",
"North-East Facing  Dual Level Living",
" state  Living At Its Finest",
"Affordable Way To Enter The Market",
"Your Own Private Resort!",
"Renovate And Reward Yourself",
"Designer Townhome Without The Associated Price Tag",
"Huge Courtyard For Outdoor Living",
" numberofbedrooms  Bedroom Low-Set Brick & Tile",
"Spacious Riverside  property t In Prestigious  street ",
"Renovated Abode In The Heart Of  suburb ",
"Beautifully Renovated   property ",
"Affordable Apartment In The Heart Of  suburb ",
"Fantastic Buying In The Heart Of  suburb ",
"Magnificent Corner Apartment",
"Huge Loft Style Apartment",
"The Ultimate  Suburb  Townhouse",
"Position  Position  Position",
"Pet Friendly With  number  Courtyards And Big Price Drop",
"Ready To Invest Or Move In",
"Pure Perspective  Prestige And Position",
"Spacious  Ground Floor  property  In The Heart Of  Suburb ",
"A Perfect Inner City Pad",
"Charming  Private And Secure; Fully Renovated",
"Exceptional  suburb  Living In Gorgeous Apartment",
"The Ultimate Family Home",
"Charming Queenslander On Huge  lotsize sqm Block",
"One For The Family",
"Remarkably Renovated Queenslander",
"Comfy Cottage Packed With Features",
"Large Family Home In  suburb ",
"Potential  Position & Perfectly Priced",
"Entertainers Delight In  suburb ",
"Post War Stunner with Ample Charm",
"Perfect Investment Opportunity",
"Safe  Secure & Secluded",
"Premium Country Style Home",
"Sky Above  River Below  Paradise Within",
"Modern Living With A Natural Twist",
"Home On Deep Level Block With Exciting Potential",
"The Vendor Says Sell",
"Single Level Easycare Home",
"Expansive Family Entertainer In Blue Chip Locale",
"Relaxing Lifestyle Retreat Across  lotsize sqm",
"Well Kept Family Haven In Highly Regarded Location",
"Lush Tropical Oasis",
"Simply The Best",
"Bright And Brilliant On  street ",
"Gorgeous Townhome",
"The Perfect Entertainer",
"Why Not Treat Yourself",
"Time To Escape",
"Beachfront Living at its Best",
"The Lifestyle You Have Dreamed About",
"Beachside Bliss In This  numberofbedrooms  Bedroom  property ",
"Invest In This Highly Sought After Location",
"Its All About The Address",
"Renovated  Elevated & Quiet Cul-de-sac Position",
"Fully Renovated  Ready to Move In",
"Youll Want To Live Here!",
"Peacefully Located In A Popular Location",
"Calling First Home Buyers",
"Modern Urban Living",
"Private and Fully Renovated Architect Designed Home",
"Charming  Comfortable And Convenient",
"Pure Luxury Above All Else",
"Picture Perfect Everyday",
"The Rebirth Of A Classic",
"Where Luxury Lives Forever",
"Artfully Crafted With Water Views",
"Pristinely Renovated With Mountain Views",
"Life With Luxury  Indulgence And Convenience",
"Unique  Contemporary And Chic",
"Affordable Unique Riverfront Investment",
"Amazing Inner City Investment",
"Ultimate Waterside Living",
"A Flawless Lifestyle Of Unerring Distinction",
"Sophisticated  Modern  Unlimited Water Views",
"Experience Sophistication On This Spacious Property",
"Panoramic And Immersive Water Views Throughout",
"Smart  Affordable With Enormous Potential",
"Exquisite And Prestigious Sanctuary",
"Position And Potential",
"Ideal Investment with Tons Of Potential",
"Spacious  Sunny And So Well Positioned",
"Bold Beauty By The Bay",
"Modern Living & Country Charm in an Elevated Prime Position",
"Stunning Character with a Contemporary Twist",
"Rare Riverfront Retreat",
"Just Beautiful  Quality Home Your Whole Family Can Enjoy",
"Instant Appeal For Renovators  Developers And Investors",
"Brand New Luxury Home",
"Family Entertainer in Leafy Panorama",
"Luxurious Yet Affordable Family Residence",
"Stunning Serenity With Sea View",
"Perfectly Private Entertainer",
"Modern  Private And Well Located",
"Spectacular  Stylish And Spacious",
"Luxury Home In Private Setting",
"Brick Beauty With Water Views",
"Convenient  Contemporary Living With Treetop Views",
"Take In Lush  Leafy Views Above The Trees",
"Your Very Own Urban Sanctuary",
"Pure Luxury Above All Else",
"Picture Perfect In Every Way",
"Where Luxury Lives Forever",
"Iconic And Exclusive",
"Green Leafy Outlook",
"Charming Brick Gem",
"Prestigious and Luxurious But Affordable",
"Unique Investment With Huge Potential",
"Expression Of Form And Function",
"A Sanctuary Of Tranquillity On The Park",
"Light And Bright With Fantastic Water Views",
"Vast Views Of The Lake",
"The Perfect Package Of Space  Style and Comfort",
"Tranquil Views Over Tree-lined Park",
"Ultimate Peace And Privacy",
"Contemporary Design With Sparkling Water Views",
"Magnificent Estate of Grand Proportions",
"Cosmopolitan Living",
"Luxurious Architect Designed Magnificence with Fireplace",
"Stylishly Renovated Charmer",
"Completely Renovated And Private Family Retreat",
"Is This The Perfect Family Home?",
"A Private Sanctuary On Huge Block",
"Elegantly Renovated Family Living",
"Views & Great Investment Opportunity",
"Investment Opportunity Right Near The Beach",
"Investment Opportunity Overlooking The Park",
"Elevated Apartment With Sweeping Iconic Views",
"Priced to Sell! Superb Value",
"Designed For Comfortable Modern Living",
"Charming & Affordable",
"As Close To Perfect As It Gets",
"Single Level With Genuine Family Appeal",
"Spacious City Loft ‰ÛÒ Lifestyle Options Galore",
"A Style Of Its Own",
"Family Home Of Space And Flexibility",
"Calling All Savvy Investors",
"Stylish Renovated Unit Only walking distance To The Beach",
"Cheapest Brick and Tile House in  Suburb ",
"Sought After  Suburb  Opportunity",
"Brand New Townhouses",
"Location  Space And Liveability",
"Impeccably Revitalised  Charming Inner City Haven",
"Quality Home Without The Pricetag",
"Penthouse At Apartment Price",
"Sophisticated  numberofrooms  Bedroom With City Views",
"Truly An Entertainers Delight",
"Stunning River and City Views  Design & Lifestyle",
"A Solid Brick And Hardwood Build",
"An Absolute Gem For City Living",
"A House of Immense Charm and Casual Elegance",
"A Striking New Family Home",
"Boasting a Superb Location",
"Simply Stunning",
"Big Block in Prime Position",
"Quality Addition to Your Portfolio",
"Meticulously Renovated",
"Luxurious Lifestyle With Captivating Views",
"The Envy Of All City Dwellers",
"A Private Sanctuary Enjoying River Views",
"Comfortable  Quiet  Luxury",
"Superb Convenient Location With A Functional Family Home",
"The Ultimate Urban Address",
"Grand Living Spaces With An Air Of Elegance",
"Location  Location  Location",
"Sky Above  River Below  Paradise Within",
"Fully Furnished  floorno  Floor Stunner With River Views",
"Designer Style With Leafy Parkland Views",
"This Property Is All About Location",
"Priced To Sell!",
"Prized Parkview Location",
"Quiet and Highly Desirable",
"Ground Floor Unit in Great Location",
"Absolute Riverfront Living",
"Fantastic City  River And Gardens Views",
"Artists Ideal",
"Breezy  Brand New  Beautiful",
"Innovative Designed Inner City Haven",
"Quiet Privacy And Plenty Of Space",
"A Quiet Retreat Suited To Inner City Living",
"Views  Versatility And Veritable Value",
"Rare Heritage City Stunner",
"Skylines Best Buy",
"Surpassing Expectation",
"Your Dream Home Is Here",
"Modern City Apartment Offering Comfort & Style",
"The Best Of City Living.",
"Convenience With A Touch Of Serenity",
"Park Views From An Urban Oasis",
"Spacious Contemporary Haven Overlooking Parklands",
"Incredible River Views  Amazing Location  Perfect Investment",
"Refurbished And Fully Furnished With Terrific Mountain Views",
"Sure To Catch Your Eye",
"Family Home With Expansive Outdoor Deck",
"Modern Home In An Unbeatable Location",
"Better Than Just A Townhouse",
"Prestigious New Residence With Sweeping City Views",
"Stunning Contemporary Home With City Views",
"Luxury House And Land Package In  buildingname  Estate",
"Rare Huge Family Home",
"If Position  Presentation & Price Are Important",
"Affordable Riverfront",
"Luxury Riverside Contemporary",
"Eye-catching Queenslander",
"Captivating Views & A Spacious Design",
"Chic  Sharp & Sure To Impress",
"Style And Sophistication",
"Beautiful  Modern  Spacious",
"Classic Meets Contemporary",
"Picturesque City  River And Park Views",
"Meticulously Crafted  Exceptionally Appointed",
"Absolute Perfection In A Stunning Riverfront Location",
"Stylish Sanctuary",
"Best Home  Best Location  Best Value",
"Clear Instructions to Sell",
"Motivated Sellers",
"Great First Home",
"Lock It and Leave It Lifestyle",
"Ultimate Family Resort Lifestyle",
"Amazing Space  Top Floor  Riverfront Living",
"Be The Envy Of Your Friends",
"Riverside Escape When Lifestyle Matters",
"Charm  Architecture and True Convenience",
"Modern and Manicured Lakeside Living",
"A Blue Chip Investment Opportunity",
"Full Brick Single Level Home In A Premier Location",
"Ground Floor Apartment In Exclusive Complex",
"Fully Furnished Apartment For The Investors",
"Immaculately Presented Apartment.",
"Expansive Family Home With Loads Of Potential",
"Attention First Home Buyers And Investors!",
"Fantastic Opportunity To Enter The Market",
"Snap Up This Great Investment",
"Snap It Up Before Its Sold!",
"Nicely Presented Townhouse In Great Location",
"Sensational New Development",
"Nothing To Do But Move In",
"Exclusive Pad In Unparalleled Position",
"Beach and City Lifestyle",
"Stylish Inner City Apartment",
"Chic City Living",
"Live A Royal Lifestyle",
"Prized Water Front Lifestyle",
"Spacious Pad In The Heart Of The City",
"North Facing Views Over The City",
"Exquisitely Renovated Family Home",
"A True Modern Day Queenslander",
"Location  Lifestyle and Liveability",
"A Modern Entertainer On A Flat Block",
"A Modern Entertainer On A Corner Block",
"Quiet  Peaceful & Room To Move",
"Fantastic Family Home  So Much To Offer",
"Full of Charm & Priced to Sell Fast",
"Big Block Big Potential",
"Beautifully Presented  Exceptional Value",
"Waterside Grandeur",
"Unique Classic Queenslander Style Home",
"Quiet Street  Immaculate Home  Huge Yard",
"Top Location  Low Price!",
"Luxurious  Architect Designed Magnificence",
"Top Location  Value Price!",
"Waterfront Contemporary Chic",
"Stylish Entertainer Close To Park",
"Stylish Entertainer Close To River",
"Stylish Riverside Entertainer",
"Stylish Entertainer Close To Beach",
"Stylish Corner Block Entertainer",
"Stylish Hillside Entertainer",
"Stylish Lakeside Entertainer",
"Stylish Private Entertainer",
"A Benchmark For Family Living",
"The Ultimate Family Home",
"Statement Living On A Grand Scale",
"Riverside Rarity",
"Stunning Modern Queenslander",
"Stunning Modern Queenslander On  lotsize sqm Block",
"Stunning Modern Queenslander On Elevated Block",
"Stunning Modern Queenslander On Flat Block",
"Stunning Modern Queenslander On Corner Block",
"Renovated Family Home In Premier Position",
"Exemplifying Style  Serenity & Lifestyle",
"Prestigious Penthouse With Spectacular Views",
"Rare Riverfront Apartment",
"Waterfront Landmark",
"Exceptional Family Home On Acreage",
"Truly Sensational Family Home",
"Family Friendly  suburb  Home On  lotsize ",
"Elevated Family Home On  lotsize sqm Allotment",
"Sought After Family Home On  lotsize ",
"Luxury Boutique Apartment",
"Landmark Residence With Superb Finishes",
"Sought After Family Home",
"Classic Family Queenslander",
"Low Maintenance Family Living",
"The Ultimate Family Resort",
"Stunning Home With Views",
"Your Own Family Sanctuary",
"Low Maintenance Living In Peaceful Location",
"Large Family Home With Pool",
"Uninterrupted Water Views",
"Price Reduced To Sell!",
"Dont Compromise On Location Or Lifestyle",
"Ground Floor Apartment With Outdoor Entertaining",
"Chic Apartment In  Suburb ",
"Spacious  Contemporary Apartment",
"Spacious  Modern Complex",
"Calling All Investors!",
"Add Even More Value",
"Grand Family Home on  lotsize m2",
"Stunning Family Home In A Great Location",
"A Unit With Space & Serenity",
"Spacious & Immaculate  Elevated Family Home",
"Solid Family Home Enjoying A Perfect N/E Aspect",
"Spacious & Immaculate Home With Fantastic Views Of  cityname ",
"Endless Potential  Exceptional Value",
"Great Opportunity On  lotsize m2 In Leafy  suburb ",
"Boutique Townhouse With City Views",
"Live In It Or Renovate  The Choice Is Yours",
"Impressive Family Home With Space For Everyone",
"Entertainers Delight",
" suburb  Townhouse With A Designer Feel",
"Why Build When You Can Buy As New. Immaculate",
"Large Family Home With Pool",
"Private Family Paradise",
"Grand Family Home On  lotsize m2",
"Great Opportunity In Beautiful  suburb ",
"Stunning Family Home In A Great Location",
"Low Maintenance Living In A Peaceful Location",
"Classic  suburb  Beauty",
"Brand New & Modern  noofbedrooms  Bedroom Dwelling",
"Price Reduced To Sell",
"Stunning Pole Home With Views",
"Large Post War Home On  lotsize  m2 Lot  Be Quick.",
"A Huge  lotsize m2 With Endless Potential",
"Peaceful Tranquillity",
" suburb  Cutie",
"Your Own Family Sanctuary",
"The Ultimate Family Resort",
"Lowset Spacious Family Home",
"Lovely Views And Breezes",
"Location Is The Operative Word",
"Lowset Family Home In Quiet Cul-De-Sac",
"Ultimate Family Home In Sought After Location",
"Gorgeous Cottage With So Much Potential",
"Family Haven Set On The Elevated Estate.",
"Acreage Living without the Maintenance",
"Elevated Cul-De-Sac Prestige Estate",
"Queenslander On A Huge 1024sqm Block",
"Quiet Location Next To The Park",
"Cul-De-Sac Delight. Owner Motivated To Sell",
"Spacious Family Home With Fantastic Views",
"Colonial Gem",
"River & City Views",
"Neat As A Pin In An Ultra-Convenient Location",
" suburb  Townhome",
"Live Your New Dream In Sweet Surrounds",
"The Perfect Setting To Enjoy Retirement",
"Retirement living with style and space",
"Priced To Sell Quickly",
"Potential Plus In The Heart Of  suburb ",
"Affordable Inner City Cottage",
"Renovate Or Rebuild",
"Large Family Home",
"Buy In  suburb ",
"Convenient Local With City Glimpses.",
"Instant Appeal With Future Promise",
"Prime Location  Small Complex & Size Including Rare  noofcars  Car Spaces",
"Large Family Home With Level Land In Convenient Location",
"Luxury  Location  Lifestyle. Yes You Can Have It All.",
"Interstate Transfer Forces Sale",
"Great Investment Opportunity",
"Spacious Family Home On Large Block",
" suburb  Excellence",
"5-Star Shed  lotsize m Level Land",
"Impressive Family Home",
" noofbedrooms  Bedroom House",
"Pet Friendly Unit With A Yard",
"Just Stunning",
"Prime Position & Unlimited Potential",
"Designer Home With Lush Garden Oasis",
"A Design Of Unquestionable Distinction",
"Unique Colonial Charm in the Heart of  suburb ",
"Classic Victorian Overflowing With Potential",
"Beautiful Sunlit Home In Prized Central Location",
"Victorian Home Of Convenience & Charm",
"Parkside Lifestyle Of Premium Quality",
"Stylish Parkside Haven",
"Classic Home  Ultimate City Convenience",
"Classic Style One-Level With Potential",
"Timeless Charm & Chic Cottage Appeal",
"Space & Style For All The Family",
"A Secret & Handy Location",
"Family Home In Central Location",
"Elegant Family Home",
"Walk To School  Unwind At Home",
"Chic Design  Prime Location at Exceptional Value!",
"Private Seamless Style",
"Space  Style and So Convenient",
"Attractive Entertainer In Popular Street",
"Stylish & Modern Family Home",
"Position  Space & Clever Design At A Great Price",
"Captivating Family Home",
"Parkside Lifestyle Of Premium Quality",
"A Stylish Parkside Haven",
"Classical terrace in quiet leafy pocket",
"Right House  Right Time",
"Single-Level Family Living",
"Family Home In Central  suburb  Location",
"Striking Split Level With Mountain Views",
"Dream Living In  suburb ",
"Position! Position! Position!",
"Private  Peaceful & Sensational Location",
"Located In The Top Street With Split-Level Charm",
"Cosmopolitan Living",
"Prestigious Estate Of Grand Proportions",
"Exclusive Estate of Grand Proportions",
"Amazing Estate of Grand Proportions",
"Exquisite Estate Of Grand Proportions",
"Grand Proportions In A Prestigious Estate",
"Distinguished Estate of Grand Proportions",
"Beautiful Estate of Grand Proportions",
"Grand Proportions In An Amazing Estate",
"Grand Proportions In An Exquisite Estate",
"Grand Proportions In A Beautiful Estate",
"Grand Proportions In An Exclusive Estate",
"Prestigious Beauty Of Grand Proportions",
"Exclusive Beauty Of Grand Proportions",
"Exclusive Beauty Of Grand Proportions",
"Huge & Exclusive Estate",
"Huge Prestigious Estate",
"Exclusive Estate Of Amazing Size",
"Positioned In The Heart Of  suburb ",
"Large Home Perfect For Families Or Developers",
"Light and Bright",
"Upsize Your Lifestyle While Downsizing Your Workload",
"Townhouse Living Never Looked So Good!",
"Simply Sensational",
"Renovated And Extended Family Home!",
"Rare Chance To Buy Land Within  Suburb ",
"Large Block Of Land In Convenient Location",
"Address For Success",
"Attention Investors!",
"Easy Living  Convenient Location",
"City Fringe Lifestyle",
"Inner  state  Lifestyle Without The Price tag",
"Introducing Investors To This Unique  property ",
"Stunning View  Amazing Location",
"Amazing Views And Great Location",
"Central Location  Priced To Sell",
"Future Proof Your Investment",
"Set-and-Forget Investment or a Lifestyle of Convenience",
"Split Level  property  Near Shops and Schools",
"Great Opportunity For First Home buyers Or Investors",
"Wake Up On The Top Of The World Everyday",
"Investment Opportunity!",
"Amazing Lake & City Views On Offer",
"North Facing  property ",
"Convenient Opportunity In Practical Location",
"Stunning Lake Views!",
"Enjoy The Comforts Of Living In The Heart Of  suburb ",
"Luxurious & Stylish Property In The Heart Of  suburb ",
"Outstanding North Facing Corner Apartment With Stunning Water Views",
"Taking Your Luxury Lifestyle To New Heights",
"Modern Marvel",
"Brand New Townhouses",
"Location  Size and Convenience",
"Live In One Of The Most Popular  state  Locations",
"Oh What A View!",
"High Calibre Investment Opportunity",
"Stylish Executive Living",
"Great Investment Opportunity in  suburb ",
"Perfectly Positioned",
"An Investment With Great Potential",
"Little Piece Of Paradise",
"Spoilt For Amenity And Choice",
"Immaculate Villa Offers Great Lifestyle Convenience",
"View Of The Lake! Better Be Quick",
"One Of  suburb s Best  noofbedroom   property ",
"2 Water Views! Lake & Pool",
"North Facing Ground Floor Apartment",
"Ultra-Convenient Location",
"Leafy And Secluded Ground Floor Apartment",
"Top Shelf  Top Floor Apartment",
"Top Floor & Spacious",
"Super Spot For Someone Special",
"Comfortable City Living",
"Live The Cosmopolitan Dream",
"Cosmopolitan Lifestyle",
"Top Quality Inclusions  Outstanding Complex  Great Location",
"Beautiful Loft Style Apartment",
"Executive Apartment",
"Timeless Family Acreage Estate",
"Sensational Acreage Living",
"Secluded Leafy Retreat Plus Studio",
"Perfect To Live In Or For Investment Property",
"Secluded Leafy Island Retreat + Studio",
"Just Stunning",
"Villa in Resort Style Complex Opposite Beach",
"Gorgeous Acreage With Brilliant Views",
"Renovated Beach Cottage",
"Enjoy Your Own Private Bushland Outlook",
"Priced To Sell! Prime Position!",
"High Set Beach House Overlooking Natural Bushland",
"Vacant Land In Quiet Cul-De-Sac",
"Great Position  Quality Finishes & Cracking Value!",
"Low Maintenance Home With A Beautiful Outlook",
" suburb  Beach House In Central Location",
"Views & North Facing",
"Residential Land For Sale",
"Luxury Resort Apartment Ocean Views",
"A Huge Development Potential!",
"Modern Holiday Sack Close To Beach",
"Elevated Vacant Block",
"Level Vacant Building Block",
"Fabulous Views Across The Island!",
"Spectacular Sweeping Views",
"Golden Opportunity",
"A Downsizing Delight",
"The Whole Kit & Caboodle",
"Renovated Brilliance In Parkside Location",
"Lifestyle  Location  Low Maintenance",
"What A Bargain!",
"Make Your Move",
"Nest Or Invest!",
"An Apart-meant For YOU!",
"Trendy Lifestyle or Great Investment!",
"Near City Terrace Living at Its Best",
"Step Inside And Be Surprised!",
"Fresh and Modern Popular  suburb  Apartment!",
"Spacious Family Entertainer",
"Contemporary Family Home Enjoying Tranquil Location",
"Grand Family Entertainer With Pool",
"An Idyllic Family Retreat In A Quiet Cul-De-Sac",
"Immaculate Easycare Duplex Central To Amenities",
"WOW! Simply Stunning!",
"Low Maintenance Home In Great Location",
"Resort-like Family Home With Majestic Views",
"Ideal Family Home Or Investment",
"Magnificent Residence With Golf Course Views",
"Resort Style Living At Its Best",
"Duplex Villa",
"Family Home in Sought-After Area",
"Potential Duel Living on The Golf Course",
"Potential Duel Living in  cityname ",
"Spacious Family Home With Amazing Views",
"Spacious & Modern With Amazing Water Views",
"Charming & Cozy With Amazing Ocean Views",
"Artistic & Contemporary With Eye-catching Street Appeal",
"Luxuriously Chic With Amazing Water Views",
"Luxuriously Chic With Amazing City Views",
"Luxuriously Chic With Amazing Elevated Views",
"Luxuriously Chic With Amazing Sunset Views",
"Beautiful And Breezy Beach house With Amazing Ocean Views",
"Beautiful & Breezy Beach house",
"Double Storey Dream Home With Amazing Ocean Views",
"Double Storey Dream Home With Amazing Water Views",
"Double Storey Dream Home With Amazing City Views",
"Double Storey Dream Home With Amazing Mountain Views",
"Double Storey Dream Home With Amazing Golf Course Views",
"Double Storey Dream Home With Picturesque Views",
"Great Investment Opportunity",
"Modern studio right in the heart of  suburb !",
"Bright Studio Apartment With Iconic Views",
"Beautiful Studio Apartment With Iconic Views",
"Bright Studio Apartment With City Views",
"Luxurious Near New Studio Apartment",
"Beach-Inspired Art Deco",
"Studio apartment situated in the  buildingname ",
"Chic City Pad Offers Bright Generous Interiors",
"Delightful Studio Apartment In The Heart Of  suburb ",
"Beautifully Refurbished North Facing Unit",
"Beautifully Refurbished North Facing Studio Apartment",
"Beautifully Refurbished North Facing Apartment",
"Beautifully Refurbished North-East Facing Apartment",
"Beautifully Refurbished North-East Facing Studio Apartment",
"Beautifully Refurbished North-East Facing Unit",
"All About The Beach Lifestyle? This Ones For You!",
"Affordable Beachside Surfers Studio Apartment",
"Brand New Beachside Studio Apartment",
"The Ultimate Setting  Location And Lifestyle",
"Reduced To Sell Fast  Be Quick",
"Luxury Beachfront Apartment",
" suburb  Beachside Location",
"Prime Beachside Investment",
"Prime Lakeside Investment",
"Prime Riverfront Investment",
"Prime Parkside Investment",
"Brand New Luxury Residences",
"North-Facing Sought After Location",
"Island Getaway For Astute Investment",
"Enjoy The Island Lifestyle",
"Private And Beautiful Waterfront Property",
"Combining Vintage Charm With Superb Potential",
"Superior Waterfront Home",
"Mega Value",
"Luxury On The Beach",
"Secure Investment For The Future",
"Luxury  suburb  Townhouse",
"Luxury  suburb  Apartment",
"Investors Take Note",
"Light  Airy And Private",
"Island Vista- Beautiful Water View Home",
"Ultra Private Resort-Style Waterfront Home",
"Fabulous Location -Close To Shops And Transport",
"Lifestyle  Luxury and Location!",
"Quiet Leafy Area  Near Sea",
"Tranquil Setting",
"Superbly Presented Classic Heritage",
"High-End Luxury Living With Sweeping Views",
"Golfers Dream! Modern Home With Golf Course Views",
"Large Family Home Ready And Waiting",
"Spectacular Water Views",
"Spectacular River Views",
"Spectacular Bay Views",
"Spectacular Mountain Views",
"Spectacular Bush Views",
"Make This Your New Home or Investment Property",
" noofbedrooms  Bedroom Beachside Unit",
" noofbedrooms  Bedroom Bayside Unit",
" noofbedrooms  Bedroom Riverfront Unit",
"Immaculate  Fully Fenced Acreage",
"World Class Location  Superb Potential",
"Cosmopolitan Living",
"Modern Home With Water Views",
"Modern Home With River Views",
"Modern Home With Bay Views",
"Modern Home With Mountain Views",
"Peaceful Tranquillity",
"Stunning Views Out Over The Bay",
"Presentation  Privacy And Position",
"Tranquillity At Your Door Step",
"Bright  Bold And Brimming",
"Massive Waterfront Home",
"Massive Riverfront Home",
"Massive Beachside Home",
"Massive Bayside Home",
"Charming Federation Queenslander",
"Perfect Island Lifestyle Living",
"Absolutely Spectacular River Views",
"Absolutely Spectacular Water Views",
"Absolutely Spectacular Bay Views",
"Absolutely Spectacular Mountain Views",
"Absolutely Spectacular Bush Views",
"Charming Gem",
"Spacious Yet Cozy",
"Fall In Love With The Island Lifestyle.",
"Fresh Stylish  Contemporary Design",
"Island Beauty With Amazing Water Views",
"Island Beauty With Amazing Ocean Views",
"High-End Luxury Living With Water Views",
"High-End Luxury Living With Sweeping River Views",
"High-End Luxury Living With Sweeping Mountain Views",
"High-End Luxury Living With Sweeping Water Views",
"Little Brick Beauty",
"Elegance By The Bay",
"Exquisite Bayside Living",
"Exquisite Beachside Living",
"Exquisite Riverfront Living",
"Exquisite Waterfront Living",
"Modern And Vibrant Beachside Beauty",
"Modern And Vibrant Bayside Beauty",
"A Little Piece Of Paradise",
"Modern And Vibrant Riverfront Beauty",
"Modern And Vibrant Waterfront Beauty",
"Your Mediterranean Retreat",
"Brick And Tile Beauty",
"Prestigious Beachside Home",
"Prestigious Bayside Home",
"Prestigious Riverfront Home",
"Prestigious Waterfront Home",
"Picture Perfect Acreage",
"An Immaculate Home Overlooking  suburb ",
"Ocean Resort Living At Its Best",
"Luxury Penthouse Apartment",
"Resort Apartment With Water Views",
"Resort Apartment With River Views",
"Resort Apartment With Bay Views",
"Resort Apartment With Bush Views",
"Absolute Luxury With Stunning Surrounds",
"Gorgeous  Private  Beach House",
"Gorgeous Ocean Views",
"Gorgeous River Views",
"Gorgeous Water Views",
"Gorgeous Bay Views",
"Gorgeous Mountain Views",
"Gorgeous Bush Views",
"Beachside Getaway",
"Riverfront Getaway",
"Waterfront Getaway",
"Terrace In Fabulous Location",
"Lifestyle  Position  Convenience",
"Capture The Charm  Love The Space  Live The Location",
"Penthouse Chic Amongst the Cafe Culture",
"Top Floor  Top Spot  Top Choice",
"Family Sized Vintage Charm",
"Compelling Contemporary Concepts",
"Where Sophistication Meets Industrial Style",
"Contemporary Design  Cosmopolitan Lifestyle",
"Exclusive Indulgence By The Bay",
"Luxury Beachside Haven",
"Luxury Bayside Haven.",
"Luxury Riverfront Haven.",
"Luxury Waterfront Haven.",
"Luxury & Lifestyle Come Together",
"Lifestyle Appeal In A Light-Filled Abode",
"Light And Bright Modern Apartment",
"Elevated Victorian Apartment With Timeless Charm",
"Panoramic Penthouse Prize",
"Funky First Home",
"Tranquil Arts And Crafts Home",
"Glamorous Beachside Victorian",
"Glamorous Bayside Victorian",
"Glamorous Riverfront Victorian",
"Glamorous Waterfront Victorian",
"An Effortless Life Of Luxury In A Dream Location",
"The Scene Is Serene",
"International Standard Penthouse  Superb Views  Spectacular Design",
"Vintage Charm  Designer Style",
"Luxury Lifestyle Living So Close To Town",
"Riverside Family Refinement",
"Quality And Class In The Heart Of  Suburb ",
"Perfect Apartment  Perfect Location!",
"Light And Bright With Show-Stopping Views",
"Smart Designer Apartment With Panoramic City Views",
"Impressively Sized  First Class Living",
"Light Filled And Stylish Apartment",
"Stunning Blue Chip Opportunity In  suburb ",
"Quality And Amenity",
"Amazing Art-deco Apartment",
"Beauty By The Bay",
"Beauty By The Beach",
"Beauty By The River",
"Art-deco Elegance  Renovated With Flair",
"Tranquil leafy setting with stunning ocean views",
"Tranquil leafy setting with stunning city views",
"Tranquil leafy setting with stunning harbour views",
"Pure Resort Style Luxury",
"The Space To Breathe           Live  Relax And Entertain",
"A World Class Luxurious Penthouse",
"A World Class Luxurious Apartment",
"A World Class Luxurious Unit",
"Gracious Tudor-Style Apartment",
"Gracious Tudor-Style Domain",
"Ground Floor Art Deco With Courtyard",
"The Best Of Inner City Living",
"The Best Of Country Living",
"The Best Of Island Living",
"Spacious Family Comfort",
"Spacious Modern Living In A Captivating Deco Setting",
"Freestanding  Family-Sized Space And Fabulously Positioned",
"Spectacular Colonial Home",
"Exclusive And Exquisite",
" suburb  Lifestyle  Spectacular Panoramic Views",
"Start Out In Style",
"Exquisite Living  Exclusive Location",
"Modern Contemporary And Secure",
"Renovated  Sunny  Peaceful",
"Fresh  Fabulous and Freestanding",
"Immaculate Family Home",
"Immaculate Family Abode",
"Lush Inner City Retreat",
"Lush Inner City Sanctuary","Enviable Corner Location",
"Completely Private Behind Its Elegant Lines",
"Stunning Victorian Terrace In Highly Sought After Location",
"Sleek  Stylish And Spacious",
"Blank Canvas  Potential Masterpiece",
"Central  Peaceful And Affordable",
"Complete Lifestyle Convenience",
"Urban Retreat In Lifestyle Location",
"Architecturally Unique Residence",
"Superb Luxury  Surprisingly Affordable",
"Light  Luxury And Vivid Views",
"A New Benchmark In Luxury Living",
"Heritage Living Like Never Before",
"Enjoy Inner City Resort Style Living",
"Quiet And Convenient Oasis",
"Modern Architectural Appeal",
"Sophisticated Style On The City Fringe",
"Dynamic And Super Stylish Pad",
"Breathtaking Northern Views",
"Breathtaking City Views",
"Breathtaking Garden Views",
"Breathtaking Water Views",
"Breathtaking Beach Views",
"Breathtaking Mountain Views",
"Renovated Inner City Abode",
"Premier Location  First Class Design",
"Immaculate From Top To Toe",
"Art Deco Beauty With Parkside Views",
"Art Deco Beauty With City Views",
"Art Deco Beauty With River Views",
"Art Deco Beauty With Water Views",
"Art Deco Beauty With Bay Views",
"Art Deco Beauty With Ocean Views",
"A Wonderful Lifestyle Awaits",
"Heritage Charm",
"Luxurious  suburb  Living",
"Original Charm  Designer Style",
"A City Edge Lifestyle To Love",
"Memorable Modern Living In  buildingname ",
"Epitomizes Inner City Lifestyle",
"Private Tree Top views With Garden Surrounds",
"City Heritage Brilliance",
"Quiet And Secluded Inner City Living",
"Iconic Architectural Prestige In A Premier Cul De Sac",
"Defining Inner City Chic",
"Captivating And Modern In The City",
"Elegant Renovation  Irresistible Classic",
"Sleek and Stylish  Ultra Modern Apartment",
"Chic and Stylish  Ultra Modern Dream Home",
"Sleek and Stylish  Ultra Modern Loft",
"Sleek and Stylish  Ultra Modern Unit",
"Sleek and Stylish  Ultra Modern Villa",
"Sleek and Stylish  Ultra Modern Residence",
"Sleek and Stylish  Ultra Modern Penthouse",
"Perfect Harmony Of Position And Views",
"Renovated Victorian Primed For Lifestyle",
"Vintage Elegance And Fabulous Central Position",
"Stunning And Expansive Family Entertainer",
"Exclusive Rustic Penthouse",
"Exclusive Rustic Apartment",
"Exclusive Rustic Unit",
"Exclusive Rustic Loft",
"Exclusive Rustic Residence",
"Exclusive Rustic Home",
"Exclusive Rustic Townhouse",
"Light And Bright With Show Stopping Views",
"Smart  Sophisticated And Contemporary",
"Stunning Blue Chip Opportunity",
" suburb  Perfection",
"Contemporary Sophistication  Suburban Lifestyle",
"Unrivalled City Edge Living",
"Renovate  Rebuild Or Redevelop",
"Ultimate Prestige Living",
"Space  Privacy And Stunning Views",
"Timeless Style  Distinction And Premium Location",
"Glamorous Heritage Apartment Oozing With Character",
"Glamorous Heritage Loft Oozing With Character",
"Glamorous Heritage Unit Oozing With Character",
"Glamorous Heritage Penthouse Oozing With Character",
"Glamorous Heritage Townhouse Oozing With Character",
"Position  Poise and Panoramic Views",
"Architect Designed With An Eye On Quality.",
"Space And Style In A Sophisticated Package",
"Light  Luxury And Leafy Views",
"Light  Luxury And River Views",
"Light Filled Luxury And Water Views",
"Light  Luxury And Bay Views",
"Light Filled Luxury And Mountain Views",
"Light Filled Luxury And Bush Views",
"Light Filled Luxury And Ocean Views",
"Light Filled Luxury And City Views",
"Light Filled Luxury And Parkside Views",
"Heritage And Modern  Ideally Matched",
"Stylish Living In The Heart Of  cityname ",
"Stylish Living In The Heart Of  suburb ",
"Designed To Entertain",
"Incredible Urban Oasis",
"Ultra Chic Inner City Pad",
"Ultra Chic Inner City Apartment",
"Ultra Chic Inner City Unit",
"Ultra Chic Inner City Penthouse",
"Ultra Chic Inner City Townhouse",
"Unparalleled  Uncompromising  Unbelievable",
"An Uninterrupted City Vista",
"Big Hearted Entertainer Inside And Out",
"Spectacular Scale and Luxury",
"An Unforgettable Statement In Style",
"Imposing Light Filled Family Residence",
"Marvellous Modern Living Moments",
"Exceptional Views And Exclusive Surrounds",
"Building Of Timeless Grace And Grandeur",
"Quality  Class And Chic Contemporary Style",
"Incomparable Benchmark Of Style & Sophistication",
"Perched High And Mighty",
"Smart And Secure In A Sensational Setting",
"Period Beauty  Modern Living",
"Wonderful Lifestyle  Winning Location",
"The Sights  The Lights And The Style",
"Victorian Charm  Vibrant Location",
"Inner City Lifestyle And Convenience",
"Modern Apartment In Buzzing City Precinct",
"Natural sunlight  long private outlooks",
"Location  Lifestyle And Elevated City Views",
"Location  Lifestyle And Elevated River Views",
"Location  Lifestyle And Elevated Water Views",
"Location  Lifestyle And Elevated Mountain Views",
"Location  Lifestyle And Elevated Bush Views",
"Location  Lifestyle And Elevated Ocean Views",
"Location  Lifestyle And Elevated Parkside Views",
"Vibrant  Stylish  Urban Living",
"City Sanctuary",
"Bright And Airy Studio Apartment",
"Brand New Terrace Style Residence",
"Brand New Loft Style Pad",
"Brand New Art-deco Style Apartment",
"Brand New Art-deco Style Townhouse",
"Brand New Art-deco Style Unit",
"Spacious And Contemporary Living",
"Location And Convenience",
"Indulgent Inner City Penthouse",
"Indulgent Inner City Apartment",
"Indulgent Inner City Unit",
"Indulgent Inner City Loft",
"Indulgent Inner City Townhouse",
"Captivating Convergence Of Classic And Contemporary",
"Chic Harbourside Studio",
"Chic Beachside Studio",
"Chic Bayside Studio",
"Chic Waterfront Studio",
"Chic Riverfront Studio",
"Parkside Stylish Apartment",
"Riverfront Stylish Apartment",
"Waterfront Stylish Apartment",
"Beachside Stylish Apartment",
"Bayside Stylish Apartment",
"Oceanfront Stylish Apartment",
"Harbourside Stylish Apartment",
"Art Deco Glamour And Awesome River Views",
"Art Deco Glamour And Awesome Water Views",
"Art Deco Glamour And Awesome Moutain Views",
"Art Deco Glamour And Awesome Bush Views",
"Art Deco Glamour And Awesome Ocean Views",
"Art Deco Glamour And Awesome City Views",
"Art Deco Glamour And Awesome Park Views",
"Wonderful Tranquil Home",
"Wonderful Tranquil Apartment",
"Wonderful Tranquil Unit",
"Wonderful Tranquil Loft",
"Wonderful Tranquil Penthouse",
"Wonderful Tranquil Townhouse",
"Character  Comfort And Potential",
"The Pinnacle Of Inner City Living",
"Modern  Stylish And Convenient",
"Sought After Parkside Locale",
"City Living Offering Comfort And Convenience",
"A Fusion Of Style  Comfort And Luxury",
"An Offering Of Exquisite Pedigree",
"Stunning Combination Of Elevation  Space And Location",
"Grand Classic Family House With Glittering Harbour Views",
"Grand Classic Family House With Glittering River Views",
"Grand Classic Family House With Glittering Water Views",
"Grand Classic Family House With Glittering Bay Views",
"Grand Classic Family House With Mountain Views",
"Grand Classic Family House With Glittering Ocean Views",
"Grand Classic Family House With Glittering City Views",
"Grand Classic Family House With Glittering Park Views",
"Chic And Comfortable",
"Modern Style In A Hip Inner City Locale",
"Architectural Masterpiece",
"Stunningly Presented Inner City Pad",
"Stunningly Presented Inner City Apartment",
"Stunningly Presented Inner City Unit",
"Stunningly Presented Inner City Penthouse",
"Stunningly Presented Inner City Loft",
"Stunningly Presented Inner City Townhouse",
"Contemporary City Living",
"Spacious And Bright In The City",
"Warm And Cozy Near New Apartment",
"Warm And Cozy Near New Unit",
"Warm And Cozy Near New Loft",
"Warm And Cozy Near New Residence",
"Warm And Cozy Near New Penthouse",
"Warm And Cozy Near New Townhouse",
"Sophisticated Meets Urban",
"Oversized Elegance",
"Secluded Hideaway In The Heart Of  suburb ",
"Secluded Hideaway In The Heart Of  cityname ",
"Sophisticated Indoor And Outdoor Entertainer",
"Intimate City Skyline Views",
"North Facing Luxury In Harbour Foreshore Setting",
"Gorgeous Outlooks Over  suburb ",
"Gorgeous Outlooks Over  cityname ",
"Gorgeous Outlooks Over  cityname ",
"Inner City Rarity",
"Urban Village Living Meets Harbourside Tranquillity",
"Urban Village Living Meets Beachside Tranquillity",
"Urban Village Living Meets Bayside Tranquillity",
"Chic Urban Living",
"Quiet Gem In A Bustling Inner City Hub",
"Luxurious Designer Living with Spectacular Views",
"Tuscan Charm",
"Relaxed Family Living With A Private Outdoor Oasis",
"Simply Spectacular Family Home",
"Exceptional Family Space In Idyllic Surrounds",
"Commanding Elevated Family Home",
"Affordable Luxurious Lifestyle",
"Functional  Neat And Light Filled Design",
"Lush And Leafy",
"Prestige Apartment In An Exclusive Beachside Address",
"Prestige Apartment In An Exclusive Bayside Address",
"Prestige Apartment In An Exclusive Riverfront Address",
"Prestige Apartment In An Exclusive Waterfront Address",
"Prestige Apartment In An Exclusive Oceanfront Address",
"Prestige Apartment In An Exclusive Harbourside Address",
"Prestige Penthouse In An Exclusive Beachside Address",
"Prestige Townhouse In An Exclusive Beachfront Address",
"Exceptional Family Lifestyle",
"Stunning And Stylish Contemporary Family Home",
"Stunning And Stylish Contemporary Apartment",
"Stunning And Stylish Contemporary Unit",
"Stunning And Stylish Contemporary Penthouse",
"Stunning And Stylish Contemporary Townhouse",
"Brand New Modern  Contemporary Living",
"Desirable Large Corner Block With City Views",
"Desirable Large Corner Apartment With City Views",
"Desirable Large Corner Unit With City Views",
"Desirable Large Corner Apartment With River Views",
"Desirable Large Corner Apartment With Water Views",
"Desirable Large Corner Apartment With Bay Views",
"Spacious  Elegant And Light Filled",
"Modern Minimalist Style",
"Tranquil Courtyard Townhouse",
"Tranquil Courtyard Apartment",
"Tranquil Courtyard Unit",
"Tranquil Courtyard Home",
"Exclusive Hillside Living With Stunning City Views",
"Suburban Sanctuary",
"Expansive Entertainer Featuring Panoramic Views",
"Expansive Entertainer Featuring River Views",
"Expansive Entertainer Featuring Water Views",
"Expansive Entertainer Featuring Bay Views",
"Expansive Entertainer Featuring Mountain Views",
"Expansive Entertainer Featuring Bush Views",
"Expansive Entertainer Featuring Ocean Views",
"Expansive Entertainer Featuring City Views",
"Expansive Entertainer Featuring Golf Course Views",
"Expansive Entertainer Featuring Park Views",
"Renovate  Extend Or Rebuild",
"Exclusively Designed And Utterly Faultless",
"A Place To Call Home",
"Affordable Do Up",
"First In Best Addressed!",
"Paint Your Future",
"Choose Your Own Adventure!",
"Its Just So Handy!",
"Owners Say Sell Were Leaving",
"Brand New Luxury Home!",
"Executive  Excellence With Style",
"Sitting On A Large Coastal Corner Site",
"PRICED TO SELL!",
"What A Stunner",
"Little Treasure In  Suburb ",
"Sun Drenched Seclusion",
"Family Indulgence",
"Solid Value With Easy Care",
"Renovated Home With Potential",
"A Very Neat Package",
"Ultimate First Home Opportunity",
"Nearly New Affordable Home",
"Single-Level Standalone",
"Elevated And Elegant",
"Ticks All The Boxes!",
"One Of Suburb Finest",
"Instantly Appealing: Perfect",
"Superbly Appointed Bedroom",
"Sunny Family Haven",
"Too Good To Ignore",
"Vendor Wants This Gone!",
"First Class Family Living!",
"Your Familys Best Move",
"Motivated Vendor!",
"Sunny Modern Family Home",
"Brand New Dream Home",
"Resort Style Living At Home",
"Embrace The #Trendy",
"Move In & Enjoy!",
"The Very Best Views Wow!",
"Come Home To The Good Life!",
"Pure Privacy With Pool",
"Sensational Hassle Free Living",
"Family Fun Good Times Start Here",
"Stunning Family Home With Options!",
"Privacy  Presentation And Motivation",
"Brand New And Ready For You",
"Luxurious  Spacious and Exceptional Value",
"Colonial Style Home",
"Colonial Style Apartment",
"Colonial Style Unit",
"Colonial Style Home",
"Colonial Style Townhouse",
"A Luxurious Urban Gem",
"Spacious Light Filled Beauty With Brilliant Lake Views",
"Spacious Light Filled Beauty With Brilliant Mainland Views",
"Spacious Light Filled Beauty With Brilliant Garden Views",
"Brand New Designer Haven Of Superior Luxury And Convenience"
);
?>